services:

  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: zellular/zsequencer:latest

  proxy:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    image: zellular/zsequencer-proxy:latest