services:

  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: zellular/zsequencer:latest

  batch_aggregator_proxy:
    build:
      context: ./batch_aggregator_proxy  # Path to the service directory
      dockerfile: Dockerfile  # Dockerfile name (optional if named `Dockerfile`)
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1