services:
  zsequencer:
    container_name: zsequencer-node
    image: zellular/zsequencer:latest
    volumes:
      - "${ZSEQUENCER_BLS_KEY_FILE}:/app/bls_key.json"
      - "${ZSEQUENCER_ECDSA_KEY_FILE}:/app/ecdsa_key.json"
      - "${ZSEQUENCER_SNAPSHOT_PATH}:/db"
      - "${ZSEQUENCER_APPS_FILE}:/app/app.json"
      - "${ZSEQUENCER_NODES_FILE}:/app/nodes.json"
    environment:
      - ZSEQUENCER_BLS_KEY_FILE=/app/bls_key.json
      - ZSEQUENCER_ECDSA_KEY_FILE=/app/ecdsa_key.json
      - ZSEQUENCER_SNAPSHOT_PATH=/db
      - ZSEQUENCER_APPS_FILE=/app/app.json
      - ZSEQUENCER_NODES_FILE=/app/nodes.json
    env_file:
      - .env

  zsequencer_proxy:
    container_name: zsequencer-proxy
    image: zellular/zsequencer-proxy:latest
    ports:
      - "80:${ZSEQUENCER_PROXY_PORT}"
    env_file:
      - .env
