services:
  zsequencer:
    container_name: zsequencer-node
    image: zellular/zsequencer:latest
    volumes:
      - "${ZSEQUENCER_BLS_KEY_FILE}:/app/bls_key.json"
      - "${ZSEQUENCER_ECDSA_KEY_FILE}:/app/ecdsa_key.json"
      - "${ZSEQUENCER_SNAPSHOT_PATH}:/db"
    environment:
      - ZSEQUENCER_BLS_KEY_FILE=/app/bls_key.json
      - ZSEQUENCER_ECDSA_KEY_FILE=/app/ecdsa_key.json
      - ZSEQUENCER_SNAPSHOT_PATH=/db
    ports:
      - "${ZSEQUENCER_PORT}:${ZSEQUENCER_PORT}"  # Binds ZSEQUENCER_PORT on host
    env_file:
      - .env
