services:
  zsequencer:
    container_name: zsequencer-node
    image: zellular/zsequencer:latest
    network_mode: host
    ports:
      - "${ZSEQUENCER_PORT}:${ZSEQUENCER_PORT}"
    volumes:
      - "${ZSEQUENCER_BLS_KEY_FILE}:/app/bls_key.json"
      - "${ZSEQUENCER_ECDSA_KEY_FILE}:/app/ecdsa_key.json"
      - "${ZSEQUENCER_SNAPSHOT_PATH}:/db"
      - "${ZSEQUENCER_APPS_FILE}:/app/app.json"
      - "${ZSEQUENCER_NODES_FILE}:/app/nodes.json"
    environment:
      - ZSEQUENCER_BLS_KEY_FILE=/app/bls_key.json
      - ZSEQUENCER_ECDSA_KEY_FILE=/app/ecdsa_key.json
      - ZSEQUENCER_SNAPSHOT_PATH=/db
      - ZSEQUENCER_APPS_FILE=/app/app.json
      - ZSEQUENCER_NODES_FILE=/app/nodes.json
    env_file:
      - .env

  batch_aggregator_proxy:
    build:
      context: ./batch_aggregator_proxy  # Path to the service directory
      dockerfile: Dockerfile  # Dockerfile name (optional if named `Dockerfile`)
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1