services:

  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: zellular/zsequencer:latest

  batch_aggregator_proxy:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    image: zellular/zproxy:latest