services:
  zsequencer:
    container_name: zsequencer-node
    image: zellular/zsequencer:latest
    network_mode: host
    volumes:
      - "${ZSEQUENCER_BLS_KEY_FILE}:/app/bls_key.json"
      - "${ZSEQUENCER_ECDSA_KEY_FILE}:/app/ecdsa_key.json"
      - "${ZSEQUENCER_SNAPSHOT_PATH}:/db"
    environment:
      - ZSEQUENCER_BLS_KEY_FILE=/app/bls_key.json
      - ZSEQUENCER_ECDSA_KEY_FILE=/app/ecdsa_key.json
      - ZSEQUENCER_SNAPSHOT_PATH=/db
    env_file:
      - .env

  batch_aggregator_proxy:
    container_name: zsequencer-proxy
    image: zellular/zproxy:latest
    ports:
      - "${ZSEQUENCER_PROXY_PORT}:${ZSEQUENCER_PROXY_PORT}"
    env_file:
      - .env
